### ISSUE TITLE
Current version is missing the fail_action param

### ISSUE THREAD

**Issue by patrickwyler** [zaproxy/action-full-scan#12]
Hi
Could you create a new version tag? The current version **v.1.0** is missing the _fail_action_ param which is described in the readme.

- [Difference between master/v0.1.0](https://github.com/zaproxy/action-full-scan/compare/v0.1.0...master)
- [Useful commit with the missing param](https://github.com/zaproxy/action-full-scan/commit/d05844c6e533559abd656ca1ff396f2976a41b49)

May the readme example could be expanded also with all options:
```
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://www.zaproxy.org/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          fail_action: true
```
