### ISSUE TITLE
Feature: add authenticated scans

### ISSUE THREAD

**Issue by hazcod** [zaproxy/action-full-scan#5]
Add the necessary input variables to configure the ZAP authentication toggles to perform authenticated scans in your pipeline.

.e.g.
```yaml
  zap_scan_cluster:
    runs-on: ubuntu-latest
    name: Scan k8s cluster
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          issue_title: Vulnerability Scan Results
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: owasp/zap2docker-weekly
          target: https://cluster.ironpeak.be/
          rules_file_name: .github/zap.ignore
          cmd_options: '-a'
          
          http_login_form: '/app/login'
          http_login_http_username: 'testuser'
          http_login_http_password: ${{ secrets.ZAP_USER_PW }}
```

**Comment by psiinon** [comment]
Would definitely like to see this, but its not a simple as that ;)

**Comment by mmogy** [comment]
You can run authenticated scans by supplying a context file via `cmd_options`.

1. Using ZAP Desktop, create and configure a [context](https://www.zaproxy.org/docs/desktop/start/features/contexts/)
2. Export the context to a file (File > Export Context...)
    a. ⚠️ **This file may contain credentials!** ⚠️ If you configured passwords into the context, they will be present in the file in base64-encoded format. You should manually edit the context file to replace them with a placeholder string.
3. **After removing all base64-encoded passwords**, add the context file to the repository where the ZAP Action is running
4. Set up secrets in your repository containing the original base64-encoded passwords from the context file. These are properly encrypted within GitHub.
5. Configure your ZAP Action to read the secrets, place them into the context file, and feed the context file to the runner.

Example:
```
...
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      - name: Context Setup
        env:
          # Set a previously defined secret as an environment variable for this step:
          B64PASSWORD: ${{secrets.B64PASSWORD}}
        # Replace the "PLACEHOLDER" string in the context file with the real base64-encoded password:
        run: |
          sed -ie "s/PLACEHOLDER/${B64PASSWORD}/" $GITHUB_WORKSPACE/ctx_file.context
      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: http://example.com
          # Additional command line options
          # -j   runs the AJAX spider
          # -U   specifies which user to select from the context file
          cmd_options: -j -U "my_username" -n /zap/wrk/ctx_file.context
```
